version: '3.7'
services:
  sons-of-the-forest:
    image: jammsen/sons-of-the-forest-dedicated-server:latest
    container_name: sons-of-the-forest
    volumes:
      - ${APP_DATA_DIR}/data:/steamcmd/sons-of-the-forest
    restart: unless-stopped
    networks:
      - tipi_main_network
    ports:
      - ${NETWORK_INTERFACE:-0.0.0.0}:8766:8766/udp
      - ${NETWORK_INTERFACE:-0.0.0.0}:27015:27015/udp
      - ${NETWORK_INTERFACE:-0.0.0.0}:27015:9700/udp
      - ${NETWORK_INTERFACE:-0.0.0.0}:27016:27016/tcp
    environment:
      - SERVER_NAME=${SERVER_NAME:-MyForestServer}
      - SERVER_PASSWORD=${SERVER_PASSWORD:-1234}
      - STEAM_BRANCH=${STEAM_BRANCH:-public}
      - TZ=${TZ:-America/Sao_Paulo}
    labels:
      traefik.enable: false
      runtipi.managed: true

networks:
  tipi_main_network:
    external: true
