version: '3.9'
services:
  sons-of-the-forest-dedicated-server:
    container_name: sons-of-the-forest-dedicated-server
    image: jammsen/sons-of-the-forest-dedicated-server:latest
    restart: always
    environment:
      PUID: 1000
      PGID: 1000
      ALWAYS_UPDATE_ON_START: true
      SKIP_NETWORK_ACCESSIBILITY_TEST: true
    ports:
      - ${NETWORK_INTERFACE:-0.0.0.0}:8766:8766/udp
      - ${NETWORK_INTERFACE:-0.0.0.0}:27016:27016/udp
      - ${NETWORK_INTERFACE:-0.0.0.0}:9700:9700/udp
    volumes:
      - ${APP_DATA_DIR}/game:/opt/sonsoftheforest
    networks:
      - tipi_main_network